name: Build Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: farhadbaig
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t farhadbaig/python-docker-app:latest .

      - name: Push Docker image
        run: |
          docker push farhadbaig/python-docker-app:latest

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 host to known hosts
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh ubuntu@"$EC2_HOST" << 'EOF'
            cd ~/python-docker-app

            echo "Pulling latest application image..."
            docker compose pull app

            echo "Updating application container..."
            docker compose up -d app

            echo "Waiting for application..."
            sleep 5

            echo "Running health check..."
            curl -f http://localhost/health

            echo "Checking containers..."
            docker compose ps
          EOF
